name: PrusaSlicer autobuild example trigger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  trigger-autobuild:
    uses: Felix-Rm/prusaslicer-autobuild/.github/workflows/autobuild.yml@main
    with:
      only_if_new_release: true
      create_release_copy: true
      upstream_repo: prusa3d/PrusaSlicer
      upstream_ref: latest:release
      downstream_repo: Felix-Rm/prusaslicer-autobuild # replace with your fork
      downstream_feature_branches: ';' # replace with your feature branches, seperated by ';'
      release_tag_prefix: 'autobuild_'
      release_name_prefix: 'Autobuild for Release of '
      release_body_prefix: |
        This is an autobuild release of PrusaSlicer.
        There are no guarantees that this build is stable, no additional testing has been done.
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}